# Run unit tests for your Python application
# (1) What's the name of your GitHub Actions?
name: C4W3-Ungraded-Lab

# Controls when the action will run. 
# (2) What's the trigger for this GitHub Action?
on:
  # Triggers the workflow on push request events only when there are changes in the desired path
  push:
    paths:
      - 'course4/week3-ungraded-labs/C4_W3_Lab_4_Github_Actions/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# (3) What should this Action do once it's been triggered?
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        # Use bash as the shell
        shell: bash
        # Specify the working directory for the worflow
        working-directory: course4/week3-ungraded-labs/C4_W3_Lab_4_Github_Actions/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: Test with pytest
        run: |
          cd app/
          pytest
